stages:
  - build
  - deploy


variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .cache/pip
    - .venv


site-build:
  stage: build
  image: python:3.10
  before_script:
    - apt update
    - apt install -y pandoc
    - pip install poetry
    - poetry --version
    - poetry config virtualenvs.in-project true
    - poetry install -vv
  script:
    - cd site
    - poetry run make html
  artifacts:
    paths:
      - site/build/html


pages:
  stage: deploy
  image: alpine
  script:
    - cp -r site/build/html public
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

