stages:
  - docker-image-build
  - build
  - deploy


variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_TLS_CERTDIR: "/certs"
  GIT_SUBMODULE_STRATEGY: normal

build-and-push-build-image:
  stage: docker-image-build

  image: docker:latest
  services:
    - docker:dind
  tags:
    - dind
  script:
    - export BUILDX_NO_DEFAULT_ATTESTATIONS="1"
    - echo Creating Docker image $DOCKER_IMAGE_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE_TAG docker-build
    - docker push $DOCKER_IMAGE_TAG

  rules:
    - changes:
      - docker-build/Dockerfile


site-build:
  stage: build
  needs: []
  image: $DOCKER_IMAGE_TAG
  cache:
    key: site-build-${CI_COMMIT_REF_SLUG}
    paths:
      - .cache/pip
      - .venv
  before_script:
    - export PATH=$HOME/.local/bin:$PATH
    - uv --version
  script:
    - cd site
    - uv run make html
  artifacts:
    paths:
      - site/build/html
  rules:
    - when: always


pages:
  stage: deploy
  image: alpine
  script:
    - cp -r site/build/html public
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

colabize:
  stage: deploy
  needs: []
  image: $DOCKER_IMAGE_TAG
  before_script:
    - export PATH=$HOME/.local/bin:$PATH
    - uv --version
    - git config --global user.email "gitlab-ci@dummy.co.uk"
    - git config --global user.name "GitLab CI"
    - git config --global url."https://chrism0dwk:${IDDINF_GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
  script:
    - INPUTDIR=site/source/iddinf
    - OUTPUTDIR=colab/iddinf
    - mkdir -p $OUTPUTDIR
    - |+
      for NB in $(find $INPUTDIR -maxdepth 1 -name "*.ipynb")
      do
        OUTPUTFILE=$OUTPUTDIR/$(basename $NB)
        echo Processing $NB to $OUTPUTFILE
        python scripts/myst_exercise_to_colab.py $NB -o $OUTPUTFILE
      done
  after_script:
    - cd colab
    - git status
    - git checkout main
    - git status
    - git add .
    - git commit -m "Add Colab-ized notebook from $CI_PROJECT_URL ($CI_COMMIT_SHORT_SHA)"
    - git push
  rules:
    - when: always
