stages:
  - build-docker
  - build
  - deploy


variables:
  DOCKER_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  DOCKER_TLS_CERTDIR: "/certs"


build-push-docker-image:
  stage: build-docker

  image: docker:latest

  services:
    - docker:dind

  script:
    - echo Creating Docker image $DOCKER_IMAGE_TAG
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_TAG

  rules:
    - changes:
      - pyproject.toml
      - poetry.lock
      - Dockerfile

site-build:
  stage: build

  image: $DOCKER_IMAGE_TAG

  script:
    - echo `pwd`
    - poetry shell
    - cd site
    - make html

  artifacts:
    paths:
      - site/build/html

pages:
  stage: deploy

  image: $DOCKER_IMAGE_TAG

  script:
    - cp -r site/build/html public

  artifacts:
    paths:
      - public

  only:
    variables:
      - $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

